# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the following format: <em>+91__________</em>.', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='clinitian',
            name='HealthCare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operations.HealthCare'),
            preserve_default=False,
        ),
    ]
