# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180920_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcare',
            options={'verbose_name': 'Primary Health Care', 'verbose_name_plural': 'Primary Health Cares'},
        ),
        migrations.AlterField(
            model_name='baby',
            name='blood_group',
            field=models.CharField(choices=[(b'a_positive', b'A Positive'), (b'a_negative', b'A Negative'), (b'b_positive', b'B Positive'), (b'b_negative', b'B Negative'), (b'o_positive', b'O Positive'), (b'o_negative', b'O Negative'), (b'ab_positive', b'AB Positive'), (b'ab_negative', b'AB Negative')], max_length=10, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='baby',
            name='gender',
            field=models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='administered_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.HealthCare'),
        ),
    ]
