# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20181015_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='administered_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phc', to='operations.HealthCare'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='phc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='operations.Appointment'),
        ),
    ]
