# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20181015_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinerecord',
            old_name='phc',
            new_name='appointment',
        ),
    ]
