# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20181015_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='administered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='tentative_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinerecord',
            unique_together=set([('appointment', 'vaccine')]),
        ),
        migrations.AlterUniqueTogether(
            name='vaccineschedule',
            unique_together=set([('baby', 'vaccine')]),
        ),
    ]
