# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20181015_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinerecord',
            name='dose',
            field=models.CharField(default='Generic Dosage', help_text='name of vaccine dose with Company name', max_length=90),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='status',
            field=models.CharField(choices=[(b'cancelled', b'Cancelled'), (b'scheduled', b'Scheduled'), (b'administered', b'Administered')], default='scheduled', max_length=20, verbose_name='Vaccine Status'),
        ),
    ]
