# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-28 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20181029_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='dose',
        ),
        migrations.AlterField(
            model_name='baby',
            name='special_notes',
            field=models.CharField(default='NA', help_text='Any Medical conditions such as allergies are to be mentioned here', max_length=400, verbose_name='Special Notes'),
        ),
    ]
