# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20190327_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
