# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_notification_notif_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[(b'info', b'info'), (b'success', b'success'), (b'error', b'error')], default='info', max_length=40),
            preserve_default=False,
        ),
    ]
