# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-12 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Notification Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[(b'info', b'info'), (b'success', b'success'), (b'error', b'error')], max_length=40, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
