# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20190712_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='text_notifications',
        ),
        migrations.AddField(
            model_name='parent',
            name='text_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
