# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20190723_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'scheduled', b'Scheduled'), (b'cancelled', b'Cancelled'), (b'approved', b'Approved')], default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
