# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20190807_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='week',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'completed', b'Completed'), (b'scheduled', b'Scheduled'), (b'cancelled', b'Cancelled')], default='scheduled', max_length=50),
        ),
    ]
