# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auto_20190807_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name': 'Baby', 'verbose_name_plural': 'Babies'},
        ),
        migrations.AlterModelOptions(
            name='clinitian',
            options={'verbose_name': 'Clinician', 'verbose_name_plural': 'Clinicians'},
        ),
        migrations.AlterModelOptions(
            name='vaccinerecord',
            options={'verbose_name': 'Vaccine Record', 'verbose_name_plural': 'Vaccine Records'},
        ),
        migrations.AlterModelOptions(
            name='vaccineschedule',
            options={'verbose_name': 'Vaccine Schedule', 'verbose_name_plural': 'Vaccine Schedules'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'completed', b'Completed'), (b'scheduled', b'Scheduled'), (b'partial', b'Partially Completed'), (b'cancelled', b'Cancelled')], default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[(b'info', b'info'), (b'success', b'success'), (b'error', b'error'), (b'danger', b'danger')], default='info', max_length=40, verbose_name='Notification Type'),
        ),
    ]
