# Generated by Django 3.0.4 on 2020-04-01 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0021_auto_20200331_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinitian',
            name='user',
            field=models.OneToOneField(default=1, help_text='Create a new user to add as a  Clinitian. This would be used as login credentials.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcare',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the following format: <em>+91__________</em>.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the following format: <em>+91__________</em>.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=1, help_text='Create a new user to add as a Parent or Guardian. This would be used as login credentials.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='vaccine',
            field=models.CharField(choices=[(0, (('bcg', 'BCG'), ('opv', 'OPV 0'), ('hepb1', 'HEP-B 1'))), (6, (('dt1', 'DTwP 1'), ('ipv1', 'IPV 1'), ('hepb2', 'HEP-B 2'), ('hib1', 'HIB 1'), ('rota1', 'Rotavirus 1'), ('pcv1', 'PCV 1'))), (10, (('dt2', 'DTwP 2'), ('ipv2', 'IPV 2'), ('hib2', 'HIB 2'), ('rota2', 'Rotavirus 2'), ('pcv2', 'PCV 2'))), (14, (('dt3', 'DTwP 3'), ('ipv3', 'IPV 3'), ('hib3', 'HIB 3'), ('rota3', 'Rotavirus 3'), ('pcv3', 'PCV 3'))), (24, (('opv1', 'OPV 1'), ('hepb3', 'HEP-B 3'))), (36, (('opv2', 'OPV 2'), ('mmr1', 'MMR-1')))], max_length=20, verbose_name='Vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='vaccine',
            field=models.CharField(choices=[(0, (('bcg', 'BCG'), ('opv', 'OPV 0'), ('hepb1', 'HEP-B 1'))), (6, (('dt1', 'DTwP 1'), ('ipv1', 'IPV 1'), ('hepb2', 'HEP-B 2'), ('hib1', 'HIB 1'), ('rota1', 'Rotavirus 1'), ('pcv1', 'PCV 1'))), (10, (('dt2', 'DTwP 2'), ('ipv2', 'IPV 2'), ('hib2', 'HIB 2'), ('rota2', 'Rotavirus 2'), ('pcv2', 'PCV 2'))), (14, (('dt3', 'DTwP 3'), ('ipv3', 'IPV 3'), ('hib3', 'HIB 3'), ('rota3', 'Rotavirus 3'), ('pcv3', 'PCV 3'))), (24, (('opv1', 'OPV 1'), ('hepb3', 'HEP-B 3'))), (36, (('opv2', 'OPV 2'), ('mmr1', 'MMR-1')))], max_length=20, verbose_name='Vaccine'),
        ),
    ]
