# Generated by Django 3.0.4 on 2020-04-01 07:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_auto_20200401_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinitian',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please use the following format: <em>+91__________</em>.', max_length=128, null=True, region=None),
        ),
    ]
