# Generated by Django 3.0.5 on 2019-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_auto_20200410_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('late', 'Late'), ('dropped_out', 'Dropped Out'), ('completed', 'Completed')], max_length=20, null=True, verbose_name='vaccination_status'),
        ),
    ]
