# Generated by Django 3.0.5 on 2020-04-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_baby_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='administered_at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='phc', to='operations.HealthCare'),
            preserve_default=False,
        ),
    ]
